name: Build

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Init submodule
      run: |
        git submodule update --init --recursive

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        cd ./Maverick
        python -m pip install --upgrade pip
        pip install -r prod_req.txt

    # Get build cache
    - uses: actions/checkout@v4
      with:
        ref: 'cache'
        path: './build_cache'

    - name: Build site
      run: |
        # 复用图片解析缓存
        mkdir ./Maverick/cached_imgs
        cp ./build_cache/sizeinfo.json ./Maverick/cached_imgs 2>/dev/null || true
        rm -rf ./build_cache/.git

        cd ./Maverick
        python ./build.py -c "../conf.py"

        # 保存图片缓存
        cd ..
        cp ./Maverick/cached_imgs/sizeinfo.json ./build_cache 2>/dev/null || true

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      env:
        PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./dist
      with:
        emptyCommits: false

    - name: Save build cache
      uses: peaceiris/actions-gh-pages@v4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: cache
        PUBLISH_DIR: ./build_cache
      with:
        emptyCommits: false
