name: Build

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        cd ./Maverick
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build site
      run: |
        cd ./Maverick
        python mvrk.py --config ../conf.py --source_dir ../src/ --build_dir ../dist/

    - name: Deploy to GitHub Pages
      run: |
        cd ./dist
        git init
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git branch -M main
        git add .
        git commit -m "Deploy to GitHub Pages"
        git push --force --quiet "https://${{ secrets.PERSONAL_TOKEN }}@github.com/jamesdd/jamesdd.github.io.git" main:gh-pages
